Routing
titu/canvas-consumer pull request #5
Opened 2017-08-06 10:04 UTC by titu

Routing implemented for the specified end-points

**NOTE**: this PR contains the changes made in the past [PR for DB Connect](https://github.com/titu/canvas-consumer/pull/4)

2017-08-06 17:46 UTC, arealmaas requested changes

2017-08-06 17:46 UTC, AlmaasAre commented on routes/router.js
> +    app.post('/link-account', api.linkAccount);
If we keep every routing-logic here, it's gonna be a huge file in the end. How about moving all the app.post('link-ccount') etc inside the api? And just use courseApi.init(app) or something here. Then we have control over the API-path in the api-files as well.

2017-08-06 18:29 UTC, titu commented on routes/router.js
> +    app.post('/link-account', api.linkAccount);
💯 👍

2017-08-07 06:34 UTC, AlmaasAre commented on api/courses.js
> +let getCourses = (request, response) => {
beautiful <3

2017-08-07 06:34 UTC, arealmaas approved these changes

2017-08-07 17:46 UTC, titu commented on api/courses.js
> +let getCourses = (request, response) => {
thank you :)

2017-08-07 18:00 UTC, merged